language: python
python:
- 2.6
- 2.7
- 3.3
- 3.4
- 3.5
- nightly
- pypy
- pypy3
install:
- pip install -e .[build,s3,elasticsearch]
- pip list
script:
- nosetests --with-coverage --cover-package=tubing
notifications:
  email:
  - rcorsaro@gmail.com
deploy:
  provider: pypi
  user: Robert.Corsaro
  password:
    secure: brqUGKoMpA1UeKMoqgtdvsaCy4K2LG4blOaiJm6e5VbruSasYofdZcGObLC905qbW/fId2mRG96FrVErz0bQrnx6c+4ghkB+cFKujr55VG3QfHcr5gZBq/DPgYlY8ZteWm1333ieB1ZSEbsllHsRODJF4xjEpV2OPhR0C3MoxA303GW3ejlg0lk98Ny3T8j3hFMqp4ycV+kUNLylPtKlFTsvcOmRmZ3hBuA5bA+1k/Xdk3/3t190PMkWyzIrMGzCBB6ZyGqWsG8aj04wfUWdZYhkU38LuSx7ZetMxS/H2NkWpVDrpGGKPCHQo6Fd8idS4Ozi/7R5e/16QRNoJLYUjJex78HnP6Eq9rO0Ayi+SjoRC8YPfliXcOyyatJztwp9M5qQTlcbI0ps6OTYH4JbTB23tzoUHKXaO3JYagcPLbOX5wLd5kwGs093yZ4Tc7EKc76o0gjDqARtFlZl/QX6mhycYYcrFl9A6Q+4hWfx7+Hppppl+5wzuXodafnyudE/LAUdiL1bbANG5soJutJCUcJs/4BC+JOhCQqFBO+hYAI+oNYAsm4v9YFe+U7h7EjgFrC9szY/TsugtGLPNi75jgbHudGnXE8E45KxAc7mFroMCFBwxm2KS637g7pYolfSCuGoFFWYuqs+s/c7peZnJXEqjkp5V3OfpdVqyyiluRo=
  distributions: "sdist bdist_wheel"
  on:
    repo: dokipen/tubing
    branch: master
    branch: release
after_success:
  coveralls
